services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    volumes:
      - ./web/:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    command: "npm run dev"
    depends_on:
      - db
    networks:
      - smc-network-1

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=storemycode
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smc-network-1
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt

networks:
  smc-network-1:
    driver: bridge
